### ISSUE TITLE
0x80070422 error

### ISSUE THREAD

**Issue by d9k** [BobVul/IdleShutdown#4]
I got 0x80070422 error on startup. Probably because I run IdleShutdown v2.0.0 Alpha on Windows 10 Home and the Windows Update service is disabled.

**Comment by d9k** [comment]
Ok, I enabled windows updater back with [WU10Man](https://github.com/WereDev/Wu10Man), installed [.NET Framework 3.5 ](https://www.microsoft.com/ru-ru/download/details.aspx?id=21) and was able to start your application.

**Comment by BobVul** [comment]
The project would be quite easy to build for .NET 4. It was built for 3.5 since that's what was bundled with Windows 7.

https://github.com/BobVul/IdleShutdown/releases/tag/v2.0.0-dotnet4 should work without installing 3.5 separately.
